package com.calderagames.mpfw.graphics;

import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;

import org.lwjgl.BufferUtils;
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL13;
import org.lwjgl.opengl.GL30;

import com.calderagames.mpfw.Disposable;
import com.calderagames.mpfw.MPFW;

import de.matthiasmann.twl.utils.PNGDecoder;
import de.matthiasmann.twl.utils.PNGDecoder.Format;

public class Texture implements Disposable{

	/**Width of the texture*/
	private int width;
	/**Height of the texture*/
	private int height;
	/**Id of the texture generated by openGL*/
	private int id;
	/**File path of the texture, for loading/reloading*/
	private String filePath;
	/**Texture filter, see {@link MPFW#MPFW_NEAREST}*/
	private int filter;
	/**Texture unit, see {@link MPFW#MPFW_TEXTURE0}*/
	private int texUnit;
	/**Boolean flag that states if the texture is loaded*/
	private boolean loaded;
	
	/**
	 * Constructs a texture with the provided texture filter (See: {@link MPFW#MPFW_NEAREST})
	 * and texture unit (See: {@link MPFW#MPFW_TEXTURE0}). The constructor checks the file path, decode
	 * the file and stores the width and height of the texture but doesn't load the texture into memory,
	 * use {@link #load()} for that.
	 * @param filePath path to the texture
	 * @param filter texture filter, see {@link MPFW#MPFW_NEAREST}
	 * @param texUnit texture unit, see: {@link MPFW#MPFW_TEXTURE0}
	 */
	public Texture(String filePath, int filter, int texUnit) {
		this.filePath = filePath;
		this.filter = filter;
		this.texUnit = texUnit;

		try {
			//Open file input stream
			InputStream in = new FileInputStream(filePath);
			//Decode the file
			PNGDecoder decoder = new PNGDecoder(in);
			//Get width and height
			width = decoder.getWidth();
			height = decoder.getHeight();
			//Close the steam
			in.close();
		} catch(IOException e) {
			e.printStackTrace();
		}			
	}

	/**
	 * Constructs a texture from a BufferedImage with the provided texture filter (See: {@link MPFW#MPFW_NEAREST})
	 * and texture unit (See: {@link MPFW#MPFW_TEXTURE0}), generate an openGL texture 2D and load it into memory.
	 * @param image BufferedImage to convert
	 * @param filePath path to the texture
	 * @param filter texture filter, see {@link MPFW#MPFW_NEAREST}
	 * @param texUnit texture unit, see: {@link MPFW#MPFW_TEXTURE0}
	 */
	public Texture(BufferedImage image, int filter, int texUnit) {
		width = image.getWidth();
		height = image.getHeight();
		this.filter = filter;
		this.texUnit = texUnit;

		int[] pixels = new int[image.getWidth() * image.getHeight()];
		image.getRGB(0, 0, image.getWidth(), image.getHeight(), pixels, 0, image.getWidth());

		ByteBuffer buffer = BufferUtils.createByteBuffer(image.getWidth() * image.getHeight() * 4); //4 for RGBA, 3 for RGB

		for(int y = 0; y < image.getHeight(); y++) {
			for(int x = 0; x < image.getWidth(); x++) {
				int pixel = pixels[y * image.getWidth() + x];
				buffer.put((byte) ((pixel >> 16) & 0xFF)); //Red component
				buffer.put((byte) ((pixel >> 8) & 0xFF)); //Green component
				buffer.put((byte) (pixel & 0xFF)); // Blue component
				buffer.put((byte) ((pixel >> 24) & 0xFF)); //Alpha component. Only for RGBA
			}
		}

		genTexture(buffer);

		loaded = true;
	}
	
	/**
	 * Constructs a texture from an existing openGL texture 2D, the width,
	 * height, filter and unit must be the same than when the texture was generated.
	 * @param textureId generated openGL id
	 * @param width the width of the texture
	 * @param height the height of the texture
	 * @param filter texture filter, see {@link MPFW#MPFW_NEAREST}
	 * @param texUnit texture unit, see: {@link MPFW#MPFW_TEXTURE0}
	 */
	public Texture(int textureId, int width, int height, int filter, int texUnit) {
		filePath = "null";
		id = textureId;
		this.width = width;
		this.height = height;
		this.filter = filter;
		this.texUnit = texUnit;
		
		loaded = true;
	}
	
	/**Create openGL texture 2D and load it into memory*/
	public void load() {
		if(loaded)
			return;
		
		ByteBuffer buffer = null;

		try {
			//Open file input stream
			InputStream in = new FileInputStream(filePath);
			//Decode the file
			PNGDecoder decoder = new PNGDecoder(in);
			//Get width and height
			width = decoder.getWidth();
			height = decoder.getHeight();

			//Create buffer
			buffer = ByteBuffer.allocateDirect(4 * width * height);
			//Feed buffer with the decoded data
			decoder.decode(buffer, width * 4, Format.RGBA);
			
			//Close the stream
			in.close();
		} catch(IOException e) {
			e.printStackTrace();
		}

		//Generate texture 2D
		genTexture(buffer);

		loaded = true;
	}
	
	/**Generate an openGL texture id with a byte buffer and load it into memory
	 * @param buffer byte buffer containing the texture
	 */
	private void genTexture(ByteBuffer buffer) {
		//Flip the buffer
		buffer.flip();

		//Generate the id
		id = GL11.glGenTextures();
		//Set active texture
		GL13.glActiveTexture(GL13.GL_TEXTURE0);
		//Bind the texture
		GL11.glBindTexture(GL11.GL_TEXTURE_2D, id);
		
		//Texture 2D RGBA
		GL11.glPixelStorei(GL11.GL_UNPACK_ALIGNMENT, 1);
		GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, GL11.GL_RGBA, width, height, 0, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, buffer);
		GL30.glGenerateMipmap(GL11.GL_TEXTURE_2D);

		//Set wrap parameter
		GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_S, GL11.GL_REPEAT);
		GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_T, GL11.GL_REPEAT);

		//Set texture filter
		GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, filter);
		GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, filter);

		//Unbind texture
		GL13.glActiveTexture(GL13.GL_TEXTURE0);
		GL11.glBindTexture(GL11.GL_TEXTURE_2D, 0);

		//Clear the buffer since we don't need it anymore
		buffer.clear();
	}
	
	/**Get the texture id generated by openGL*/
	public int getId() {
		return id;
	}

	/**Get the texture width*/
	public int getWidth() {
		return width;
	}
	/**Get the texture height*/
	public int getHeight() {
		return height;
	}

	/**Delete the texture and free the resources*/
	public void dispose() {
		GL11.glBindTexture(GL11.GL_TEXTURE_2D, 0);
		GL11.glDeleteTextures(id);
		id = 0;
		loaded = false;
	}
}
